CREATE DATABASE BACKUP;
USE BACKUP;

CREATE TABLE BKPCLIENTE(
	ID_BKPCLIENTE INT,
	IDCLIENTE INT,
	NOME VARCHAR(40),
	STATUS VARCHAR (10)
);
CREATE TABLE BKPTELEFONE(
	ID_BKPTELEFONE INT,
	IDTELEFONE INT,
	ID_CLIENTE INT,
	NUMERO INT(12),
	STATUS VARCHAR(10)
);

ALTER TABLE BKPCLIENTE
	ADD CONSTRAINT PK_BKPCLIENTE
	PRIMARY KEY (ID_BKPCLIENTE);
ALTER TABLE BKPCLIENTE
	MODIFY ID_BKPCLIENTE INT AUTO_INCREMENT;	

ALTER TABLE BKPTELEFONE
	ADD CONSTRAINT PK_BKPTELEFONE
	PRIMARY KEY (ID_BKPTELEFONE);
ALTER TABLE BKPTELEFONE
	MODIFY ID_BKPTELEFONE INT AUTO_INCREMENT;





/*
ALTER TABLE BKP_CLIENTE
	ADD CONSTRAINT FK_LOJA_CLIENTE_BKP_CLIENTE
	FOREIGN KEY (IDCLIENTE) REFERENCES LOJA.CLIENTE (IDCLIENTE);

ALTER TABLE BKP_TELEFONE
	ADD CONSTRAINT FK_LOJA_TELEFONE_BKP_TELEFONE
	FOREIGN KEY (IDTELEFONE) REFERENCES LOJA.TELEFONE (IDTELEFONE);
ALTER TABLE BKP_TELEFONE
	ADD CONSTRAINT FK_LOJA_CLIENTE_BKP_TELEFONE
	FOREIGN KEY (ID_CLIENTE) REFERENCES LOJA.TELEFONE (ID_CLIENTE);*/