CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(40)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	ID_CLIENTE INT,
	NUMERO INT(12)
);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);
ALTER TABLE CLIENTE
	MODIFY IDCLIENTE INT AUTO_INCREMENT;

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (IDTELEFONE);
ALTER TABLE TELEFONE
	MODIFY IDTELEFONE INT AUTO_INCREMENT;

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);


DELIMITER &

CREATE TRIGGER SALVABACKUP_CLIENTE
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKPCLIENTE VALUES (NULL, NEW.IDCLIENTE, NEW.NOME, "INSERÇÃO");
END
&

CREATE TRIGGER SALVABACKUP_CLIENTE2
AFTER UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKPCLIENTE VALUES (NULL, NEW.IDCLIENTE, NEW.NOME, "ALTERAÇÃO");
END
&

CREATE TRIGGER SALVABACKUP_TELEFONE
AFTER INSERT ON TELEFONE
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BPKTELEFONE VALUES (NULL, NEW.IDTELEFONE, NEW.ID_CLIENTE, NEW.NUMERO, "INSERÇÃO");
END
&

CREATE TRIGGER SALVABACKUP_TELEFONE2
AFTER UPDATE ON TELEFONE
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BPKTELEFONE VALUES (NULL, NEW.IDTELEFONE, NEW.ID_CLIENTE, NEW.NUMERO, "ALTERAÇÃO");
END
&

DELIMITER ;


DROP TRIGGER SALVABACKUP_CLIENTE;
DROP TRIGGER SALVABACKUP_TELEFONE;
