CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT,
	NOME VARCHAR (20),
	JAN INT,
	FEV INT,
	MAR INT
);
CREATE TABLE TOTAL(
	NOME_VENDEDOR VARCHAR (20),
	JAN INT,
	FEV INT,
	MAR INT,
	MEDIA FLOAT,
	TOTAL INT
);


ALTER TABLE VENDEDOR
ADD CONSTRAINT PK_IDVENDEDOR
PRIMARY KEY (IDVENDEDOR);

ALTER TABLE VENDEDOR
MODIFY IDVENDEDOR INT AUTO_INCREMENT;

INSERT INTO VENDEDOR VALUES (NULL, "Renan", 1000, 2543, 3467);
INSERT INTO VENDEDOR VALUES (NULL, "Karine", 3214, 1643, 2352);
INSERT INTO VENDEDOR VALUES (NULL, "Sandra", 9222, 1500, 7642);
INSERT INTO VENDEDOR VALUES (NULL, "Agatha", 1000, 345, 4324);
INSERT INTO VENDEDOR VALUES (NULL, "Sabryna", 2454, 2135, 7653);
INSERT INTO VENDEDOR VALUES (NULL, "Douglas", 1000, 1353, 2000);
INSERT INTO VENDEDOR VALUES (NULL, "Fábio", 1000, 1500, 1243);
INSERT INTO VENDEDOR VALUES (NULL, "Débora", 1000, 1500, 1254);
INSERT INTO VENDEDOR VALUES (NULL, "Ryan", 1000, 1500, 2000);

SELECT* FROM VENDEDOR;
SELECT* FROM TOTAL;


SELECT*, (JAN+FEV+MAR) AS "TOTAL", TRUNCATE(((JAN+FEV+MAR)/3),2) AS "MÉDIA" FROM VENDEDOR;


DELIMITER &

CREATE PROCEDURE INSEREVALORES2()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VNOME VARCHAR(50);
	DECLARE VAR1, VAR2, VAR3, VTOTAL INT;
	DECLARE VMEDIA FLOAT;
	
	DECLARE REG CURSOR FOR (SELECT NOME, JAN, FEV, MAR FROM VENDEDOR);
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	OPEN REG;

	REPEAT
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;
			
			INSERT INTO TOTAL VALUES (VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		END IF;

	UNTIL FIM END REPEAT;
	CLOSE REG;
END
&

DELIMITER ;	

