CREATE DATABASE CURSOS;
USE CURSOS;

CREATE TABLE CURSO(
	IDCURSO INT,
	NOME VARCHAR (40),
	VALOR FLOAT (10,2),
	DURACAO INT (4),
	REQUISITO INT
);


ALTER TABLE CURSO
ADD CONSTRAINT PK_CURSO
	PRIMARY KEY (IDCURSO);
	ALTER TABLE CURSO
		MODIFY IDCURSO INT AUTO_INCREMENT;

ALTER TABLE CURSO
ADD CONSTRAINT FK_CURSO
	FOREIGN KEY (REQUISITO) REFERENCES CURSO(IDCURSO);


INSERT INTO CURSO VALUES (NULL, "Lógica de Programação", 150.00,20,NULL);
INSERT INTO CURSO VALUES (NULL, "Java", 250.00,60,1);
INSERT INTO CURSO VALUES (NULL, "C", 249.99,60,1);
INSERT INTO CURSO VALUES (NULL, "Python", 400.00,90,2);
INSERT INTO CURSO VALUES (NULL, "MySQL", 380.50,120,3);
INSERT INTO CURSO VALUES (NULL, "Oracle DBA", 500.00,160,5);
INSERT INTO CURSO VALUES (NULL, "Desenvolvimento de Jogos", 2000.00,400,6);



SELECT* FROM V_REQUISITOS
ORDER BY VALOR;

SELECT C.NOME AS "Nome do Curso",
C.VALOR AS "Valor", 
C.DURACAO AS "Carga Horária", 
IFNULL(P.NOME, "Sem requisitos") AS "Pré-Requisitos"
FROM CURSO C
	LEFT JOIN CURSO P
	ON P.REQUISITO = C.IDCURSO
ORDER BY VALOR;





CREATE VIEW V_REQUISITOS AS
SELECT NOME, VALOR, DURACAO, 
CASE
WHEN REQUISITO IN (1) THEN "Lógica de Programação"
WHEN REQUISITO IN (2) THEN "Java"
WHEN REQUISITO IN (3) THEN "C"
WHEN REQUISITO IN (4) THEN "Phyton"
WHEN REQUISITO IN (5) THEN "MySQL"
WHEN REQUISITO IN (6) THEN "Oracle DBA"
WHEN REQUISITO IN (7) THEN "Desenvolvimento de Jogos"
ELSE "Sem Requisitos" 
END AS "Curso Requerido" FROM CURSO;	
